name: outputs-3
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        id: xyz
        run: | 
          echo "sls deploy" >> log.txt
          echo "Serverless: Stack update finished..." >> log.txt
          if grep -q "Serverless: Service files not changed. Skipping deployment" log.txt; then
            echo "::set-output name=skip_deploy::true"
          else 
            echo "::set-output name=skip_deploy::false"
          fi
  
      - if: ${{ steps.xyz.outputs.skip_deploy == 'true'}}
        name: step-2
        run: |
          echo "${{ steps.xyz.outputs.skip_deploy }}"
