name: outputs-3
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        id: xyz
        run: | 
          echo "sls deploy" >> log.txt
          echo "Serverless: Service files not changed. Skipping deployment" >> log.txt
          grep -q "Serverless: Service files not changed. Skipping deployment" log.txt

          if [ $? -eq 0 ]; then
               echo "serverless deploy --force"
          fi
